source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TAKLogger_Example' do
  pod "TAKLogger", :path => "../"
end

target 'TAKLogger_Tests' do
  pod "TAKLogger", :path => "../"
end
